// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vktfksgurakdwajvnulk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrdGZrc2d1cmFrZHdhanZudWxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NzUwNzMsImV4cCI6MjA2MDA1MTA3M30.uPljeQ8MlEhPCgthvSl8ReEYFy-HX1PX9aj4ER_H4rA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);